version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    default_reviewers:
      - 'holvonixAdvay'
    default_assignees:
      - 'holvonixAdvay'
    default_labels:
      - 'dependencies'
    commit_message:
      prefix: 'chore'
      prefix_development: 'chore'
      include_scope: true
